- name: MRISA – Install required package
  apt:
    pkg:
      - python3-pip
      - libcurl4-openssl-dev
      - libssl-dev
    state: latest
  become: yes
  tags:
    - setup

- name: MRISA – Git Clone Repo
  git:
    repo: "{{ mrisa_repo }}"
    dest: "{{ home_directory }}/{{ mrisa_app }}"
    force: yes
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: MRISA – Install specified python requirements
  pip:
    requirements: "{{ home_directory }}/{{ mrisa_app }}/requirements.txt"
    executable: pip3
  become: yes
  when: git_clone_app_finished.changed
  tags:
    - setup
    - update

- name: MRISA – Stop app
  command: forever stop "{{ mrisa_app }}"
  ignore_errors: yes
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - restart
    - stop
    - update

- name: MRISA – Start app
  command:
    cmd: forever start -a --uid "{{ mrisa_app }}" -c python3 src/server.py --port "{{ mrisa_app_port }}"
    chdir: "{{ home_directory }}/{{ mrisa_app }}"
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - restart
    - start
    - update
