- name: pull docker mongo image
  docker_image:
    source: pull
    name: mongo
    tag: "{{ mongo_version }}"

- name: ensure {{ mongodb_host_dir }} exist
  file:
    name: "{{ mongodb_host_dir }}"
    state: directory

- name: Start mongo container
  community.general.docker_container:
    name: 'mongodb'
    image: 'mongo'
    restart: yes
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ mongodb_host_dir }}:/data/db"

- name: Install iptables
  apt:
    pkg:
    - iptables
    - iptables-persistent
    update_cache: yes
    state: latest

- name: Block mongo port with iptables
  ansible.builtin.command: iptables -I DOCKER-USER -i eth0 -p tcp -m conntrack --ctorigdstport 27017 --ctdir ORIGINAL -j DROP

- name: Write iptables rules to be launched again on reboot and remove duplicates
  ansible.builtin.shell: iptables-save | uniq | iptables-restore
