all:
  children:
    dev:
      hosts:
        '127.0.0.1':
          ansible_ssh_port: 2223
          ansible_user: vagrant
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
          ansible_python_interpreter: /usr/bin/python3
          base_url: http://ota.local
          enable_https: false
