all:
  children:
    production:
      hosts:
        51.75.169.235:
          ansible_user: debian
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
          ansible_python_interpreter: /usr/bin/python3
          base_url: https://51.75.169.235
          enable_https: true
